### ISSUE TITLE
向IrinQVQ挥手！

### ISSUE THREAD

**Issue by Gah0** [lrinQVQ/android_kernel_xiaomi_msm8992_8994#1]
hi irinqvq

**Comment by lrinQVQ** [comment]
Hi,let me consider

**Comment by zah0** [comment]
hey 慢， i want to know how to merge f2fs and sdcardfs in the miui kernel，because libra was update n in micode.  may i learn c code to fix kernel

**Comment by Gah0** [comment]
我能请教一个问题吗？就是make内核时候时候出现：
Makefile:798: *** 多个目标匹配。 停止。
我已经载入了deconfig，出现这个好无奈！

**Comment by lrinQVQ** [comment]
XD 如果是libra 请载入libra_user_defconfig

**Comment by Gah0** [comment]
sry，这个comment我改了很多遍，然后自己百度也解决了一些问题，但是很可惜我也搞不懂交叉编译器的设置

回复上面问题

> 我是载入了libra_user_defconfig
> 我是用了UBERTC5.3.1去编译libra-n-oss（micode更新的那个）
> 还是出现了图中的情况
> 

![ubuntu-2018-07-11-22-36-22](https://user-images.githubusercontent.com/21006824/42579965-ffa7e138-855b-11e8-9530-b9bae1468206.png)

也就是
```
a@a:/mnt/hgfs/vm共享/Xiaomi_Kernel_OpenSource-libra-n-oss$ make -j8
Makefile:605: Cannot use CONFIG_CC_STACKPROTECTOR_REGULAR: -fstack-protector not supported by compiler
Makefile:798: *** 多个目标匹配。 停止。
```


2...我看了makefile：第798行，是这个
`vmlinux: scripts/link-vmlinux.sh $(vmlinux-deps) FORCE`

![image](https://user-images.githubusercontent.com/21006824/42579146-3bfdc78a-855a-11e8-956a-85a6ba387d57.png)



无限无奈= =XP


我改成这样，但是仍然无效。
`CROSS_COMPILE	?= APP/UBERTC-aarch64-linux-android-5.3-kernel/bin/aarch64-linux-android-gcc-5.3.1
`
结果
`Makefile:605: Cannot use CONFIG_CC_STACKPROTECTOR_REGULAR: -fstack-protector not supported by compiler`

3.....我试着把它还原到
 `CROSS_COMPILE	?= $(CONFIG_CROSS_COMPILE:"%"=%)`

XD成功编译了几秒，但是.....（还是交叉编译器问题）
```
gcc: error: unrecognized command line option ‘-mlittle-endian’
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
/mnt/hgfs/vm共享/Xiaomi_Kernel_OpenSource-libra-n-oss/./Kbuild:35: recipe for target 'kernel/bounds.s' failed
make[1]: *** [kernel/bounds.s] Error 1
Makefile:862: recipe for target 'prepare0' failed
make: *** [prepare0] Error 2

```
sry，我打算请教你，主要解决UBERTC5.3.1设置交叉编译器问题的，我修改了这个comment很多次。可能对你邮箱造成了轰炸

**Comment by lrinQVQ** [comment]
没事没事233 我看看

**Comment by Gah0** [comment]
sry，编译器搞错了，我换了这个UBERTC-arm-eabi-5.3
结果仍然是
`Makefile:605: Cannot use CONFIG_CC_STACKPROTECTOR_REGULAR: -fstack-protector not supported by compiler`
和
`Makefile:798: *** 多个目标匹配。 停止。`
交叉编译器
`CROSS_COMPILE	?= APP/UBERTC-arm-eabi-5.3/bin/arm-eabi-`

**Comment by lrinQVQ** [comment]
2333你要知道 msm8992/8994的 arm64架构的处理器
你不能用arm的gcc编译器
之前使用的aarch64是正确的
具体问题我马上测试复现下

**Comment by lrinQVQ** [comment]
然后就是make的时候请带上ARCH=arm64 你要告诉它你到底要编译哪个架构的 我相信你在载入配置文件的时候肯定是加入了这个变量的不然你也不会config成功

**Comment by lrinQVQ** [comment]
以及友情提示这些坑还只是普通的小坑后面还有一堆大坑

**Comment by Gah0** [comment]
我记得去年我直接设置menuconfig，、、XD

交叉编译器这样写（多了  `-` ）
`APP/UBERTC-aarch64-linux-android-5.3-kernel/bin/aarch64-linux-android-`
和预料中不同，失败。
我对天发誓，我真的是完全照搬的谷歌官方文档，哪里错了呢？

**Comment by lrinQVQ** [comment]
嘛 也有可能是UBERTC的bug

**Comment by Gah0** [comment]
好吧我换了这个
`git clone https://aosp.tuna.tsinghua.edu.cn/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9`
希望能成功。。

**Comment by lrinQVQ** [comment]
通常就是用google的gcc

**Comment by Gah0** [comment]
你好，问题我已经解决，的确是UBERTC的问题。我用aarch64正在进行中。 啥问题也没有。谢谢你的回答
![244_ 8072 dy1 k m 5ct](https://user-images.githubusercontent.com/21006824/42621459-747905ca-85f0-11e8-8cff-aa7b20cf5656.png)

我家里不方便上G哥..所以都是用清华的资源

**Comment by lrinQVQ** [comment]
嘛你马上就会碰到bug 了

**Comment by lrinQVQ** [comment]
@zah0 G哥相关的话
https://github.com/googlehosts/hosts/wiki/%E5%AE%9E%E9%AA%8C%E5%AE%A4-Laboratory

**Comment by Gah0** [comment]
神预判，还真出现了。
```
  CC      drivers/tspdrv/tspdrv.o
drivers/tspdrv/tspdrv.c:43:20: fatal error: tspdrv.h: No such file or directory
 #include <tspdrv.h>
                    ^
compilation terminated.
scripts/Makefile.build:308: recipe for target 'drivers/tspdrv/tspdrv.o' failed
make[2]: *** [drivers/tspdrv/tspdrv.o] Error 1
scripts/Makefile.build:455: recipe for target 'drivers/tspdrv' failed
make[1]: *** [drivers/tspdrv] Error 2
Makefile:822: recipe for target 'drivers' failed
make: *** [drivers] Error 2
```

**Comment by lrinQVQ** [comment]
https://github.com/lrinQVQ/Xiaomi_Kernel_OpenSource/commits/libra-n-oss

**Comment by lrinQVQ** [comment]
因为我才修复不久XD小米的尿性我很清楚的

**Comment by lrinQVQ** [comment]
不过这三个commit之后还有更多问题 待修复ing

**Comment by lrinQVQ** [comment]
修复了所有的编译错误 但是没猜错的话刷入后相机还是有问题的

**Comment by Gah0** [comment]
2333congratulationsss! 
> 
>

**Comment by lrinQVQ** [comment]
2333祝贺什么啦 下个bug又要来了还是l时代就有的

**Comment by Gah0** [comment]
2333看来我也要学习使用git了。你这个提交好方便。。。
其实我这次打算研究超频的（msm8992 initial overclocking），我根据RR5.7.4 ```oc6.0的那个branch一行一行的修改了`msm8992.dtsi`和`msm8992-gpu.dtsi`      还有    `qcom_cpufreq.c`和 `msm8994-XXX.c`
（仅仅是加入了一点点东西emmm）
然后还对比了其他文件，感觉好像不行。感觉好像与cpufreq有关。但是...我不会C...2333
> https://github.com/AndropaX/android_kernel_xiaomi_msm8992/commit/96b792dac05abc90ec89a3bc45c18fae1570b54a

今天mkboot放入miui9刷机包刷起来了。结果手机卡米不开机。（发热少的那种）
我还在config加入了f2fs开关。不知miui中是否可行。2333

**Comment by lrinQVQ** [comment]
和cpufreq无关的 你可能没修改对

**Comment by lrinQVQ** [comment]
暂时来说emmm也就wifi问题
曾经的相机问题也没有复现 小米还算有点良心

**Comment by Gah0** [comment]
谢谢你的帮助。

**Comment by lrinQVQ** [comment]
PS:wifi的问题是打不开 小意思啦

**Comment by lrinQVQ** [comment]
嘛2333我在测试MIUI 10 可以开机其他正常只是wifi炸了

**Comment by Gah0** [comment]
233我才知道miui10公测了，一直用着你的包..

**Comment by lrinQVQ** [comment]
2333我也是看公测了才去更新看看我的包也跟进一下

**Comment by Gah0** [comment]
我又有点搞不懂了，，我unpack了boot.img,把编译好的image改名kernel，替换文件，然后再打包。刷入手机bootloop了。(ಥ_ಥ)

**Comment by lrinQVQ** [comment]
0.0咩你怎么编译怎么打包的

**Comment by Gah0** [comment]
![screenshot_2018-08-04-03-24-37-537_com grarak kerneladiutor](https://user-images.githubusercontent.com/21006824/43662130-713347fa-9797-11e8-89b2-b4ef5ea13255.png)
成功了，刚用anykernel把img-dtb文件rename成zimage不会卡boot了
吐槽一下image-tools，我没有用这个工具成功开机过
OC貌似成功了，但我没测试稳定性。。
wifi的确是个坑，不知道官方是否会修复呢？

**Comment by Gah0** [comment]
昨晚往anykernel写入了wlan.ko相关modulea也不行。

**Comment by lrinQVQ** [comment]
wifi这个坑我得抽空修一下 加载wlan.ko没用的
官方永远不会修这个坑的

**Comment by Gah0** [comment]
我在谷歌上发现wifi这个坑，其他机型也会有

**Comment by lrinQVQ** [comment]
昂我看什么时候能修一下吧XD事情太多太多太多

**Comment by Gah0** [comment]
git push -u origin master
如果不能用怎么办？
`fatal: unable to access 'https://github.com/zah0/kernel_xiaomi_msm8992_DeadKernel_libra_miui10.git/': Could not resolve host: github.com`
添加host后...
`fatal: unable to access 'https://github.com/zah0/kernel_xiaomi_msm8992_DeadKernel_libra_miui10.git/': Couldn't connect to server`

**Comment by Gah0** [comment]
我有一个问题，我去merge`git merge FETCH_HEAD`了最新的caf文件，编译的时候是用老的libra-user-defconfig，修复了很多错误后，编译出image.gz.dtb（正常的）19个modules正常编译没有问题，，, 然后做成anykernel刷入手机，手机好像开机bootloop。我想问内核版本还与安卓版本有关么？为什么不能正常开机呢。抓了dmesg log看，感觉没什么不对，能识别出硬件。

**Comment by lrinQVQ** [comment]
如果没猜错你是单纯用merge命令merge的？

**Comment by lrinQVQ** [comment]
你用的 https…通常情况下只有读权限
最好添加一个ssh key然后用git

**Comment by Gah0** [comment]
好吧， LA.BF64.1.2.3-03310-8x92.0 这个tag，android version是07.01的.....
合并错了... 现已得知libra的tag几乎是最新的了。                                           
（从Xiaomi_OpenSource_kernle得知libra-n-oss居然是LA.BF64.1.2.3-01110-### 8x94.0   **8994**）


> 我想要内核拥有新的功能，例如sdcardfs
> 请问相应的patch应该要怎么去找？？2333

**Comment by lrinQVQ** [comment]
其实一点也不新xd甚至是两年前的版本

**Comment by lrinQVQ** [comment]
8992/8994本质上没什么大的差距2333

**Comment by Gah0** [comment]
已得到解决，谢谢你的帮助

**Comment by lrinQVQ** [comment]
小意思啦

**Comment by zah0** [comment]
CC      drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_assoc.o
drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_assoc.c:50:31: fatal error: wlan_hdd_includes.h: No such file or directory
 #include "wlan_hdd_includes.h"
                               ^
compilation terminated.
scripts/Makefile.build:308: recipe for target 'drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_assoc.o' failed
make[3]: *** [drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_assoc.o] Error 1
scripts/Makefile.build:455: recipe for target 'drivers/staging/qcacld-2.0' failed
make[2]: *** [drivers/staging/qcacld-2.0] Error 2
scripts/Makefile.build:455: recipe for target 'drivers/staging' failed
make[1]: *** [drivers/staging] Error 2
Makefile:819: recipe for target 'drivers' failed
make: *** [drivers] Error 2

搞到最后只剩一条，硬问题，解决不了

**Comment by lrinQVQ** [comment]
qcacld不是关键问题xd

**Comment by lrinQVQ** [comment]
wlan_hdd_includes.h 就在 CORE/HDD/inc/wlan_hdd_includes.h

**Comment by Gah0** [comment]
是wlan_hdd_includes.h 头文件缺失了么？

**Comment by lrinQVQ** [comment]
不是xd 小米留的巨大的坑

**Comment by Gah0** [comment]
(https://github.com/Gah0/android_xiaomi_libra_kernel/commit/1008dab7b927bb7b3ffbda71c71f3494a28017e7)
这里貌似能解决一个编译错误。。

**Comment by lrinQVQ** [comment]
咩2333 其实关键的点是https://github.com/lrinQVQ/Xiaomi_Kernel_OpenSource/blob/libra-n-oss/drivers/net/wireless/libra/Makefile

灰灰~

**Comment by lrinQVQ** [comment]
小米的GPL开源 开源.o滑稽

**Comment by Gah0** [comment]
小米开的残废源/angry
我同时编译了好几个项目，这样的问题几乎都出现在小米的源
野生的kernel我还没见过有这样的错误
我在小米的项目上开了个issue，乖奕老虎直接扔了一个他的leo_kernel给我，问题依然重现。
我现在在想，是不是我电脑问题？？？
稍微动一下/drivers/或者/include/里面的东西，很容易就出现no such or file....







```
  CC      drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_assoc.o
In file included from drivers/staging/qcacld-2.0/CORE/SERVICES/COMMON/adf/adf_os_mem.h:40:0,
                 from drivers/staging/qcacld-2.0/CORE/SERVICES/COMMON/adf/linux/adf_os_dma_pvt.h:33,
                 from drivers/staging/qcacld-2.0/CORE/SERVICES/COMMON/adf/adf_os_dma.h:39,
                 from drivers/staging/qcacld-2.0/CORE/SERVICES/COMMON/adf/adf_nbuf.h:43,
                 from drivers/staging/qcacld-2.0/CORE/VOSS/inc/vos_packet.h:60,
                 from drivers/staging/qcacld-2.0/CORE/VOSS/inc/i_vos_list.h:46,
                 from drivers/staging/qcacld-2.0/CORE/VOSS/inc/vos_list.h:73,
                 from drivers/staging/qcacld-2.0/CORE/VOSS/inc/vos_api.h:64,
                 from drivers/staging/qcacld-2.0/CORE/HDD/inc/wlan_hdd_includes.h:55,
                 from drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_assoc.c:50:
drivers/staging/qcacld-2.0/CORE/VOSS/inc/vos_cnss.h: In function 'vos_oob_enabled':
drivers/staging/qcacld-2.0/CORE/VOSS/inc/vos_cnss.h:559:2: error: implicit declaration of function 'cnss_wlan_query_oob_status' [-Werror=implicit-function-declaration]
  if (-ENOSYS == cnss_wlan_query_oob_status())
  ^
 static inline int vos_register_oob_irq_handler(oob_irq_handler_t handler,
                                                ^
drivers/staging/qcacld-2.0/CORE/VOSS/inc/vos_cnss.h: In function 'vos_unregister_oob_irq_handler':
drivers/staging/qcacld-2.0/CORE/VOSS/inc/vos_cnss.h:573:2: error: implicit declaration of function 'cnss_wlan_unregister_oob_irq_handler' [-Werror=implicit-function-declaration]
  return cnss_wlan_unregister_oob_irq_handler(pm_oob);
  ^
cc1: all warnings being treated as errors
scripts/Makefile.build:308: recipe for target 'drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_assoc.o' failed
make[3]: *** [drivers/staging/qcacld-2.0/CORE/HDD/src/wlan_hdd_assoc.o] Error 1
scripts/Makefile.build:455: recipe for target 'drivers/staging/qcacld-2.0' failed
make[2]: *** [drivers/staging/qcacld-2.0] Error 2
scripts/Makefile.build:455: recipe for target 'drivers/staging' failed
make[1]: *** [drivers/staging] Error 2
Makefile:824: recipe for target 'drivers' failed
make: *** [drivers] Error 2
```
对了，我的问题是这个= =

**Comment by Gah0** [comment]
obj-$(CONFIG_LIBRA_SDIOIF) += librasdioif.o
所以我们应该要找一个.c文件补上吗？

**Comment by Gah0** [comment]
解决了 
EXTRA_CFLAGS += -Wno-implicit-function-declaration -Wno-int-conversion

**Comment by lrinQVQ** [comment]
XD不是 修复qcacld-2.0不是关键啊23333
关键在于sdio的驱动啊

**Comment by Gah0** [comment]
sdio
我先在这里写个报告，改天再思考。。
```
  CC      drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.o
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:232:15: error: variable 'ar6k_driver' has initializer but incomplete type
 static struct cnss_sdio_wlan_driver ar6k_driver = {
               ^
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:233:2: error: unknown field 'name' specified in initializer
  .name = "ar6k_wlan",
  ^
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:233:2: error: excess elements in struct initializer [-Werror]
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:233:2: error: (near initialization for 'ar6k_driver') [-Werror]
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:234:2: error: unknown field 'id_table' specified in initializer
  .id_table = ar6k_id_table,
  ^
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:234:2: error: excess elements in struct initializer [-Werror]
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:234:2: error: (near initialization for 'ar6k_driver') [-Werror]
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:235:2: error: unknown field 'probe' specified in initializer
  .probe = hif_sdio_device_inserted,
  ^
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:235:2: error: excess elements in struct initializer [-Werror]
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:235:2: error: (near initialization for 'ar6k_driver') [-Werror]
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:236:2: error: unknown field 'remove' specified in initializer
  .remove = hif_sdio_device_removed,
  ^
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:236:2: error: excess elements in struct initializer [-Werror]
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:236:2: error: (near initialization for 'ar6k_driver') [-Werror]
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:237:2: error: unknown field 'reinit' specified in initializer
  .reinit = hif_sdio_device_reinit,
  ^
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:237:2: error: excess elements in struct initializer [-Werror]
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:237:2: error: (near initialization for 'ar6k_driver') [-Werror]
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:238:2: error: unknown field 'shutdown' specified in initializer
  .shutdown = hif_sdio_device_shutdown,
  ^
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:238:2: error: excess elements in struct initializer [-Werror]
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:238:2: error: (near initialization for 'ar6k_driver') [-Werror]
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:239:2: error: unknown field 'crash_shutdown' specified in initializer
  .crash_shutdown = hif_sdio_crash_shutdown,
  ^
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:239:2: error: excess elements in struct initializer [-Werror]
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:239:2: error: (near initialization for 'ar6k_driver') [-Werror]
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:241:2: error: unknown field 'suspend' specified in initializer
  .suspend = hif_sdio_device_suspend,
  ^
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:241:2: error: excess elements in struct initializer [-Werror]
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:241:2: error: (near initialization for 'ar6k_driver') [-Werror]
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:242:2: error: unknown field 'resume' specified in initializer
  .resume = hif_sdio_device_resume,
  ^
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:242:2: error: excess elements in struct initializer [-Werror]
drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.c:242:2: error: (near initialization for 'ar6k_driver') [-Werror]
cc1: all warnings being treated as errors
scripts/Makefile.build:308: recipe for target 'drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.o' failed
make[3]: *** [drivers/staging/qcacld-2.0/CORE/SERVICES/HIF/sdio/linux/native_sdio/src/hif.o] Error 1
scripts/Makefile.build:455: recipe for target 'drivers/staging/qcacld-2.0' failed
make[2]: *** [drivers/staging/qcacld-2.0] Error 2
scripts/Makefile.build:455: recipe for target 'drivers/staging' failed
make[1]: *** [drivers/staging] Error 2
Makefile:824: recipe for target 'drivers' failed
make: *** [drivers] Error 2

```

**Comment by lrinQVQ** [comment]
xd不用尝试修复这个了 这一块在MIUI中位于系统层中 我加入这个也只是因为我想无视MIUI的版本升级而已x

**Comment by Gah0** [comment]
但是insmod system/lib/modules/wlan.ko需要签名。。

**Comment by lrinQVQ** [comment]
嘛我自然有我的办法啦 直接在kernel中屏蔽就好

**Comment by Gah0** [comment]
wlan.ko(大小96mb)在关闭config_cnss_sdio后编译出来了。放入手机后insmod，lsmod检测成功，但按钮成了灰色的。。。我猜想，miui开发者可能对安卓中wlan某些部件进行了修补和裁剪。。。所以。。。应该是无法再miui10系统上跑了。。。可能只能应用在原生系统上。。。

**Comment by lrinQVQ** [comment]
2333因为源码他们都没有开源完啊

**Comment by Gah0** [comment]
那开发者做los是怎么编译出来wifi驱动？qwq
