### ISSUE TITLE
WIFI问题已经得到解决

### ISSUE THREAD

**Issue by Gah0** [lrinQVQ/android_kernel_xiaomi_msm8992_8994#2]
dmesg提示这个
`11-27 20:16:41.462 E/wlan    (    0): Unknown parameter `mac'`
我在早期小米的一些内核得到了这样的一个东西

添加这一个到
https://github.com/Gah0/android_kernel_xiaomi_leo/commit/332f70e62364f0968c65d0e7da30711661213aa3

已经可以正常使用WiFi,wifi热点

![tim 20190228233032](https://user-images.githubusercontent.com/21006824/53577574-de37ea00-3bb0-11e9-96f4-350c24c8c52d.png)

![screenshot_2019-02-28-23-14-24-530_com android se](https://user-images.githubusercontent.com/21006824/53577641-f60f6e00-3bb0-11e9-9c95-5949a6d01fc0.png)

**Comment by lrinQVQ** [comment]
可以可以~恭喜
